import { PrismaClient, Metal, WeightUnit, UserRole, ProductCategory } from "@prisma/client";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const adminPassword = await bcrypt.hash("Admin@123!", 12);

  const admin = await prisma.user.upsert({
    where: { email: "admin@bullion.com" },
    update: {},
    create: {
      email: "admin@bullion.com",
      name: "Platform Admin",
      passwordHash: adminPassword,
      role: UserRole.SUPER_ADMIN,
    },
  });

  const products = [
    // ── New Releases 2026 ────────────────────────────────────────────────────
    {
      name: "Archangel Michael 1oz Gold 2026",
      sku: "NBU-GOLD-1OZ-2026",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "The National Bank of Ukraine",
      year: 2026,
      category: ProductCategory.BULLION_GOLD,
      description: "2026 edition 1 oz Archangel Michael gold coin, 99.99% pure gold",
      premiumPercent: 0.045,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "American Gold Eagle 1oz 2026",
      sku: "AGE-1OZ-2026",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9167,
      mint: "US Mint",
      year: 2026,
      category: ProductCategory.BULLION_GOLD,
      description: "2026 edition 1 oz American Gold Eagle coin, 22-karat gold",
      premiumPercent: 0.04,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "Canadian Maple Leaf 1oz Gold 2026",
      sku: "CML-GOLD-1OZ-2026",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "Royal Canadian Mint",
      year: 2026,
      category: ProductCategory.BULLION_GOLD,
      description: "2026 edition 1 oz Canadian Gold Maple Leaf, 99.99% pure gold",
      premiumPercent: 0.035,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "American Silver Eagle 1oz 2026",
      sku: "ASE-1OZ-2026",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.999,
      mint: "US Mint",
      year: 2026,
      category: ProductCategory.BULLION_SILVER,
      description: "2026 edition 1 oz American Silver Eagle coin, 99.9% pure silver",
      premiumPercent: 0.15,
      minOrderQty: 20,
      images: [],
    },

    // ── Bullion Gold ─────────────────────────────────────────────────────────
    {
      name: "Archangel Michael 1oz Gold",
      sku: "NBU-GOLD-1OZ",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "The National Bank of Ukraine",
      year: 2024,
      category: ProductCategory.BULLION_GOLD,
      description: "1 oz Archangel Michael bullion gold coin, 99.99% pure gold, issued by the The National Bank of Ukraine",
      premiumPercent: 0.045,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "American Gold Eagle 1oz",
      sku: "AGE-1OZ",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9167,
      mint: "US Mint",
      year: 2024,
      category: ProductCategory.BULLION_GOLD,
      description: "1 oz American Gold Eagle coin, 22-karat gold",
      premiumPercent: 0.04,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "American Gold Eagle 1/2oz",
      sku: "AGE-HALFOZ",
      metal: Metal.GOLD,
      weight: 0.5,
      weightUnit: WeightUnit.OZ,
      purity: 0.9167,
      mint: "US Mint",
      year: 2024,
      category: ProductCategory.BULLION_GOLD,
      description: "1/2 oz American Gold Eagle coin",
      premiumPercent: 0.05,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "Canadian Maple Leaf 1oz Gold",
      sku: "CML-GOLD-1OZ",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "Royal Canadian Mint",
      year: 2024,
      category: ProductCategory.BULLION_GOLD,
      description: "1 oz Canadian Gold Maple Leaf, 99.99% pure gold",
      premiumPercent: 0.035,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "South African Krugerrand 1oz",
      sku: "SAK-GOLD-1OZ",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9167,
      mint: "South African Mint",
      year: 2024,
      category: ProductCategory.BULLION_GOLD,
      description: "1 oz South African Krugerrand, 22-karat gold",
      premiumPercent: 0.03,
      minOrderQty: 1,
      images: [],
    },

    // ── Bullion Silver ───────────────────────────────────────────────────────
    {
      name: "Ukrainian Trident 1oz Silver",
      sku: "NBU-SILVER-1OZ",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "The National Bank of Ukraine",
      year: 2024,
      category: ProductCategory.BULLION_SILVER,
      description: "1 oz Ukrainian Trident silver bullion coin, 99.99% pure silver, issued by the The National Bank of Ukraine",
      premiumPercent: 0.14,
      minOrderQty: 20,
      images: [],
    },
    {
      name: "American Silver Eagle 1oz",
      sku: "ASE-1OZ",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.999,
      mint: "US Mint",
      year: 2024,
      category: ProductCategory.BULLION_SILVER,
      description: "1 oz American Silver Eagle coin, 99.9% pure silver",
      premiumPercent: 0.15,
      minOrderQty: 20,
      images: [],
    },
    {
      name: "Canadian Maple Leaf 1oz Silver",
      sku: "CML-SILVER-1OZ",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "Royal Canadian Mint",
      year: 2024,
      category: ProductCategory.BULLION_SILVER,
      description: "1 oz Canadian Silver Maple Leaf, 99.99% pure silver",
      premiumPercent: 0.12,
      minOrderQty: 20,
      images: [],
    },
    {
      name: "Austrian Vienna Philharmonic 1oz Silver",
      sku: "AVP-SILVER-1OZ",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.999,
      mint: "Austrian Mint",
      year: 2024,
      category: ProductCategory.BULLION_SILVER,
      description: "1 oz Austrian Vienna Philharmonic silver coin",
      premiumPercent: 0.13,
      minOrderQty: 20,
      images: [],
    },

    // ── Commemorative Gold ───────────────────────────────────────────────────
    {
      name: "Hetman Khmelnytsky 1/4oz Gold",
      sku: "NBU-COMM-GOLD-QOZ",
      metal: Metal.GOLD,
      weight: 0.25,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "The National Bank of Ukraine",
      year: 2024,
      category: ProductCategory.COMMEMORATIVE_GOLD,
      description: "1/4 oz commemorative gold coin — Hetman Bohdan Khmelnytsky, proof finish, issued by the The National Bank of Ukraine",
      premiumPercent: 0.18,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "Liberty Head Double Eagle Replica",
      sku: "LHE-GOLD-1OZ",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "Private Mint",
      year: 2024,
      category: ProductCategory.COMMEMORATIVE_GOLD,
      description: "Commemorative 1 oz Liberty Head Double Eagle replica, proof finish",
      premiumPercent: 0.12,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "Golden Jubilee Commemorative 1oz",
      sku: "GJC-GOLD-1OZ",
      metal: Metal.GOLD,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "Royal Mint",
      year: 2024,
      category: ProductCategory.COMMEMORATIVE_GOLD,
      description: "Limited edition commemorative gold coin with proof finish",
      premiumPercent: 0.15,
      minOrderQty: 1,
      images: [],
    },

    // ── Commemorative Silver ─────────────────────────────────────────────────
    {
      name: "Heroes of Ukraine 1oz Silver",
      sku: "NBU-COMM-SILVER-1OZ",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9999,
      mint: "The National Bank of Ukraine",
      year: 2024,
      category: ProductCategory.COMMEMORATIVE_SILVER,
      description: "1 oz commemorative silver coin from the Heroes of Ukraine series, proof finish, issued by the The National Bank of Ukraine",
      premiumPercent: 0.28,
      minOrderQty: 5,
      images: [],
    },
    {
      name: "Morgan Silver Dollar Tribute 1oz",
      sku: "MSD-SILVER-1OZ",
      metal: Metal.SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.999,
      mint: "Private Mint",
      year: 2024,
      category: ProductCategory.COMMEMORATIVE_SILVER,
      description: "Commemorative 1 oz Morgan Silver Dollar tribute, proof quality",
      premiumPercent: 0.25,
      minOrderQty: 5,
      images: [],
    },
    {
      name: "Eagle & Shield Commemorative 5oz Silver",
      sku: "ESC-SILVER-5OZ",
      metal: Metal.SILVER,
      weight: 5,
      weightUnit: WeightUnit.OZ,
      purity: 0.999,
      mint: "Private Mint",
      year: 2024,
      category: ProductCategory.COMMEMORATIVE_SILVER,
      description: "5 oz Eagle & Shield commemorative silver bar, limited edition",
      premiumPercent: 0.2,
      minOrderQty: 1,
      images: [],
    },

    // ── Non-precious ─────────────────────────────────────────────────────────
    {
      name: "Ukrainian Coat of Arms Nickel Silver 1oz",
      sku: "NBU-NS-1OZ",
      metal: Metal.NICKEL_SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.65,
      mint: "The National Bank of Ukraine",
      year: 2024,
      category: ProductCategory.NON_PRECIOUS,
      description: "1 oz nickel silver blank bearing the Ukrainian coat of arms, issued by the The National Bank of Ukraine",
      fixedUnitPrice: 2.00,
      premiumPercent: 0,
      premiumFixed: 0,
      minOrderQty: 50,
      images: [],
    },
    {
      name: "American Platinum Eagle 1oz",
      sku: "APE-1OZ",
      metal: Metal.PLATINUM,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9995,
      mint: "US Mint",
      year: 2024,
      category: ProductCategory.PLATINUM_PALLADIUM,
      description: "1 oz American Platinum Eagle coin, 99.95% pure platinum",
      premiumPercent: 0.06,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "Canadian Palladium Maple Leaf 1oz",
      sku: "CML-PALL-1OZ",
      metal: Metal.PALLADIUM,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.9995,
      mint: "Royal Canadian Mint",
      year: 2024,
      category: ProductCategory.PLATINUM_PALLADIUM,
      description: "1 oz Canadian Palladium Maple Leaf, 99.95% pure palladium",
      premiumPercent: 0.05,
      minOrderQty: 1,
      images: [],
    },
    {
      name: "Nickel Silver Bar 1oz",
      sku: "NS-BAR-1OZ",
      metal: Metal.NICKEL_SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.65,
      mint: "Private Mint",
      year: 2024,
      category: ProductCategory.NON_PRECIOUS,
      description: "1 oz nickel silver (German silver) bar — 65% copper, 20% zinc, 15% nickel alloy",
      fixedUnitPrice: 1.50,
      premiumPercent: 0,
      premiumFixed: 0,
      minOrderQty: 50,
      images: [],
    },
    {
      name: "Nickel Silver Rounds 1oz",
      sku: "NS-ROUND-1OZ",
      metal: Metal.NICKEL_SILVER,
      weight: 1,
      weightUnit: WeightUnit.OZ,
      purity: 0.65,
      mint: "Private Mint",
      year: 2024,
      category: ProductCategory.NON_PRECIOUS,
      description: "1 oz nickel silver round coin blank, ideal for engraving and commemorative use",
      fixedUnitPrice: 1.80,
      premiumPercent: 0,
      premiumFixed: 0,
      minOrderQty: 100,
      images: [],
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: { category: product.category, mint: product.mint, fixedUnitPrice: (product as any).fixedUnitPrice ?? null },
      create: product,
    });
  }

  console.log(`Seeded admin user: ${admin.email}`);
  console.log(`Seeded ${products.length} products`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
